// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package mcp

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE0a437efDecodeGoOsspkgComMcp(in *jlexer.Lexer, out *testOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "greeting":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Greeting = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0a437efEncodeGoOsspkgComMcp(out *jwriter.Writer, in testOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"greeting\":"
		out.RawString(prefix[1:])
		out.String(string(in.Greeting))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v testOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0a437efEncodeGoOsspkgComMcp(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v testOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0a437efEncodeGoOsspkgComMcp(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *testOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0a437efDecodeGoOsspkgComMcp(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *testOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0a437efDecodeGoOsspkgComMcp(l, v)
}
func easyjsonE0a437efDecodeGoOsspkgComMcp1(in *jlexer.Lexer, out *testInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0a437efEncodeGoOsspkgComMcp1(out *jwriter.Writer, in testInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v testInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0a437efEncodeGoOsspkgComMcp1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v testInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0a437efEncodeGoOsspkgComMcp1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *testInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0a437efDecodeGoOsspkgComMcp1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *testInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0a437efDecodeGoOsspkgComMcp1(l, v)
}
func easyjsonE0a437efDecodeGoOsspkgComMcp2(in *jlexer.Lexer, out *recursiveInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "next":
			if in.IsNull() {
				in.Skip()
				out.Next = nil
			} else {
				if out.Next == nil {
					out.Next = new(recursiveInput)
				}
				if in.IsNull() {
					in.Skip()
				} else {
					(*out.Next).UnmarshalEasyJSON(in)
				}
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE0a437efEncodeGoOsspkgComMcp2(out *jwriter.Writer, in recursiveInput) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Next != nil {
		const prefix string = ",\"next\":"
		first = false
		out.RawString(prefix[1:])
		(*in.Next).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v recursiveInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE0a437efEncodeGoOsspkgComMcp2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v recursiveInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE0a437efEncodeGoOsspkgComMcp2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *recursiveInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE0a437efDecodeGoOsspkgComMcp2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *recursiveInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE0a437efDecodeGoOsspkgComMcp2(l, v)
}
