// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel(in *jlexer.Lexer, out *TimeOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel(out *jwriter.Writer, in TimeOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TimeOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TimeOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TimeOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TimeOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel1(in *jlexer.Lexer, out *TimeInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "timezone":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Timezone = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel1(out *jwriter.Writer, in TimeInput) {
	out.RawByte('{')
	first := true
	_ = first
	if in.Timezone != "" {
		const prefix string = ",\"timezone\":"
		first = false
		out.RawString(prefix[1:])
		out.String(string(in.Timezone))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TimeInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TimeInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TimeInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TimeInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel1(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel2(in *jlexer.Lexer, out *SecretOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "answer":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Answer = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel2(out *jwriter.Writer, in SecretOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"answer\":"
		out.RawString(prefix[1:])
		out.String(string(in.Answer))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SecretOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SecretOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SecretOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SecretOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel2(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel3(in *jlexer.Lexer, out *SecretInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "question":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Question = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel3(out *jwriter.Writer, in SecretInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"question\":"
		out.RawString(prefix[1:])
		out.String(string(in.Question))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SecretInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SecretInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SecretInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SecretInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel3(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel4(in *jlexer.Lexer, out *JobOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel4(out *jwriter.Writer, in JobOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JobOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JobOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JobOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JobOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel4(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel5(in *jlexer.Lexer, out *JobInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "delayMs":
			if in.IsNull() {
				in.Skip()
			} else {
				out.DelayMS = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel5(out *jwriter.Writer, in JobInput) {
	out.RawByte('{')
	first := true
	_ = first
	if in.DelayMS != 0 {
		const prefix string = ",\"delayMs\":"
		first = false
		out.RawString(prefix[1:])
		out.Int(int(in.DelayMS))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v JobInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v JobInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *JobInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *JobInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel5(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel6(in *jlexer.Lexer, out *GreetingOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "greeting":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Greeting = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel6(out *jwriter.Writer, in GreetingOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"greeting\":"
		out.RawString(prefix[1:])
		out.String(string(in.Greeting))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GreetingOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GreetingOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GreetingOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GreetingOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel6(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel7(in *jlexer.Lexer, out *GreetingInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel7(out *jwriter.Writer, in GreetingInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GreetingInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GreetingInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GreetingInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GreetingInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel7(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel8(in *jlexer.Lexer, out *FeatureOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "greeting":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Greeting = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel8(out *jwriter.Writer, in FeatureOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"greeting\":"
		out.RawString(prefix[1:])
		out.String(string(in.Greeting))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FeatureOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FeatureOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FeatureOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FeatureOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel8(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel9(in *jlexer.Lexer, out *FeatureInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Name = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel9(out *jwriter.Writer, in FeatureInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FeatureInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FeatureInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FeatureInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FeatureInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel9(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel10(in *jlexer.Lexer, out *EchoOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel10(out *jwriter.Writer, in EchoOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EchoOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EchoOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EchoOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EchoOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel10(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel11(in *jlexer.Lexer, out *EchoInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "message":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Message = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel11(out *jwriter.Writer, in EchoInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix[1:])
		out.String(string(in.Message))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v EchoInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EchoInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EchoInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EchoInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel11(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel12(in *jlexer.Lexer, out *ConfigOutput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel12(out *jwriter.Writer, in ConfigOutput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ConfigOutput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ConfigOutput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ConfigOutput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ConfigOutput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel12(l, v)
}
func easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel13(in *jlexer.Lexer, out *ConfigInput) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "value":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Value = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel13(out *jwriter.Writer, in ConfigInput) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"value\":"
		out.RawString(prefix[1:])
		out.String(string(in.Value))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ConfigInput) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ConfigInput) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD2b7633eEncodeGoOsspkgComMcpExampleModel13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ConfigInput) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ConfigInput) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD2b7633eDecodeGoOsspkgComMcpExampleModel13(l, v)
}
